import Foundation

let missingKeys = [
    "%.f days ago",
    "%.f hours ago",
    "%.f minutes ago",
    "%.f months ago",
    "%.f seconds ago",
    "%.f weeks ago",
    "%.f years ago",
    "1 minute ago",
    "Accept",
    "Activate card",
    "Activation code should be %@ characters",
    "Activation successful",
    "Add a card to wallet",
    "Add card to wallet",
    "Add card to wallet?",
    "Amount",
    "An SMS has been sent to the mobile number %@, please enter the verification code below",
    "An SMS has been sent to the mobile number %@, please enter the verification code below.",
    "An email has been sent to the email address %@, please enter the verification code below.",
    "ApplePayConfirmationBody",
    "Are you sure this card is lost?",
    "Available",
    "Cancel",
    "Cancelled",
    "Category",
    "Clear",
    "Close",
    "Closed",
    "Contact us to resolve",
    "Could not mark card as lost or stolen",
    "Create A New Password",
    "Create Password",
    "Create a new password at least 6 characters long.",
    "Create a new password at least 6 characters long. It will be used with your %@ when logging in again.",
    "Date",
    "Deactivated",
    "Dismiss",
    "Done",
    "EXP: %@",
    "Enter the activation code you received via SMS along with your mobile number",
    "Enter the verification code sent to %@",
    "Enter your email address to receive a verification code by email.",
    "Enter your mobile number to receive a verification code by SMS",
    "Enter your mobile number to receive a verification code by SMS.",
    "Expired",
    "Finish",
    "Get Verification Code",
    "How can we help?",
    "I forgot my password",
    "Inactive",
    "Keep me logged in?",
    "Locked",
    "Log in",
    "Logged in as %@",
    "Lost or Stolen",
    "Lost your card?",
    "Merchant",
    "Next",
    "Not your transaction? Contact us",
    "OK",
    "Oops, I just want to log in and see my gift card balance", "PIN tries exceeded", "Password cannot be empty", "Please confirm your password to continue.", "Please enter your activation code", "Please log in to start using your card.", "Prefix", "Redeem Gift Card", "Replaced", "Resend Verification Code", "Reset Password", "Set Password", "Settings", "Something went wrong", "Suspected Fraud", "Tap to reveal card details", "This will be used with your mobile number when logging in again (min 6 characters)", "Time", "Today", "Transaction Details", "Try Again", "Unable to retrieve terms", "Unfortunately your device is not capable of supporting Apple Pay", "Unknown error", "Update", "Username", "Username cannot be empty", "Verification", "Verification Code", "View details to use online", "Welcome!", "When contacting support quote your EAID:", "Yes it\'s gone :(", "Yesterday", "You have no\nrecent transactions", "Your application version is no longer supported", "Your card has been added to Apple Wallet", "Your card has been marked as lost", "Your card has successfully been added to Apple Wallet", "activation_code", "addPlasticCard", "address_line_1", "address_line_2", "card_number", "city", "claim_plastic_description", "claim_plastic_heading", "claim_with_info", "claim_with_info_pw", "country", "create_account", "create_account_description", "create_with_digital", "create_with_plastic", "email", "error_title", "first_name", "help_and_support", "in %.f days", "in %.f hours", "in %.f minutes", "in %.f months", "in %.f seconds", "in %.f weeks", "in %.f years", "in 1 minute", "in a few seconds", "just now", "last hour", "last month", "last week", "last year", "last_name", "loginInstruction", "logout", "manage_pin", "mobile_number", "next hour", "next month", "next week", "next year", "password", "plasticReauth", "postal_code", "postcode", "redeem_another_card", "reenter_password", "registerCardAddress", "registerCardAddressDescription", "registerCardAddressHeading", "security_code_6_digits", "showPin", "state", "suburb", "terms_and_conditions", "update_address", "zip"]") is not equal to ("["%.f days ago", "%.f hours ago", "%.f minutes ago", "%.f months ago", "%.f seconds ago", "%.f weeks ago", "%.f years ago", "1 minute ago", "Accept", "Activate card", "Activation code should be %@ characters", "Activation successful", "Add a card to wallet", "Add card to wallet", "Add card to wallet?", "Amount", "An SMS has been sent to the mobile number %@, please enter the verification code below", "An SMS has been sent to the mobile number %@, please enter the verification code below.", "An email has been sent to the email address %@, please enter the verification code below.", "ApplePayConfirmationBody", "Are you sure this card is lost?", "Available", "Cancel", "Cancelled", "Category", "Clear", "Close", "Closed", "Contact us to resolve", "Could not mark card as lost or stolen", "Create A New Password", "Create Password", "Create a new password at least 6 characters long.", "Create a new password at least 6 characters long. It will be used with your %@ when logging in again.", "Date", "Deactivated", "Dismiss", "Done", "EXP: %@", "Enter the activation code you received via SMS along with your mobile number", "Enter the verification code sent to %@", "Enter your email address to receive a verification code by email.", "Enter your mobile number to receive a verification code by SMS", "Enter your mobile number to receive a verification code by SMS.", "Expired", "Finish", "Get Verification Code", "How can we help?", "I forgot my password", "Inactive", "Keep me logged in?", "Locked", "Log in", "Logged in as %@", "Lost or Stolen", "Lost your card?", "Merchant", "Next", "Not your transaction? Contact us", "OK", "Oops, I just want to log in and see my gift card balance", "PIN tries exceeded", "Password cannot be empty", "Please confirm your password to continue.", "Please enter your activation code", "Please log in to start using your card.", "Prefix", "Redeem Gift Card", "Replaced", "Resend Verification Code", "Reset Password", "Set Password", "Settings", "Something went wrong", "Suspected Fraud", "Tap to reveal card details", "This will be used with your mobile number when logging in again (min 6 characters)", "Time", "Today", "Transaction Details", "Try Again", "Unable to retrieve terms", "Unfortunately your device is not capable of supporting Apple Pay", "Unknown error", "Update", "Username", "Username cannot be empty", "Verification", "Verification Code", "View details to use online", "Welcome!", "When contacting support quote your EAID:", "Yes it\'s gone :(", "Yesterday", "You have no\nrecent transactions", "Your application version is no longer supported", "Your card has been added to Apple Wallet", "Your card has been marked as lost", "Your card has successfully been added to Apple Wallet", "activation_code", "addPlasticCard", "address_line_1", "address_line_2", "card_number", "city", "claim_plastic_description", "claim_plastic_heading", "claim_with_info", "claim_with_info_pw", "country", "create_account", "create_account_description", "create_with_digital", "create_with_plastic", "email", "error_title", "first_name", "help_and_support", "in %.f days", "in %.f hours", "in %.f minutes", "in %.f months", "in %.f seconds", "in %.f weeks", "in %.f years", "in 1 minute", "in a few seconds", "just now", "last hour", "last month", "last week", "last year", "last_name", "loginInstruction", "logout", "manage_pin", "mobile_number", "next hour", "next month", "next week", "next year", "password", "plasticReauth", "postal_code", "postcode", "redeem_another_card", "reenter_password", "registerCardAddress", "registerCardAddressDescription", "registerCardAddressHeading", "security_code_6_digits", "showPin", "state", "terms_and_conditions", "update_address", "zip"]


missingKeys.count
